// Educational facts for each card theme - using actual card symbols
import { minecraftFacts } from './minecraftImages';

export const saintFacts: { [key: string]: { name: string; fact: string } } = {
  'saint-francis': { name: 'St. Francis of Assisi', fact: 'Founder of the Franciscan Order, St. Francis is patron saint of animals and the environment. He preached love for all creation.' },
  'saint-mary': { name: 'Virgin Mary', fact: 'Mother of Jesus Christ, venerated as the Queen of Heaven and most pure of all saints. She is called the Theotokos (Mother of God).' },
  'saint-joseph': { name: 'St. Joseph', fact: 'Foster father of Jesus and husband of Mary, patron saint of workers, fathers, and the universal Church.' },
  'saint-anthony': { name: 'St. Anthony of Padua', fact: 'Franciscan friar and Doctor of the Church, known for powerful preaching and miracles. Patron saint of lost items.' },
  'saint-teresa': { name: 'St. Teresa of Avila', fact: 'Spanish mystic, Doctor of the Church who reformed the Carmelite Order and wrote profound spiritual classics.' },
  'saint-michael': { name: 'St. Michael the Archangel', fact: 'Prince of the heavenly host who defeated Satan. Patron of police officers, soldiers, and the Church militant.' },
  'saint-peter': { name: 'St. Peter', fact: 'First Pope, leader of the apostles to whom Jesus gave the keys of the kingdom. Martyred upside-down in Rome.' },
  'saint-john': { name: 'St. John the Apostle', fact: 'The beloved disciple who wrote the Gospel of John, three epistles, and the Book of Revelation. Only apostle to die of natural causes.' },
  'saint-paul': { name: 'St. Paul', fact: 'Once persecutor of Christians, became the greatest missionary of the early Church after his conversion on the road to Damascus.' },
  'saint-luke': { name: 'St. Luke', fact: 'Physician and author of the Gospel of Luke and Acts of the Apostles. Patron saint of doctors and artists.' },
  'saint-mark': { name: 'St. Mark', fact: 'Author of the Gospel of Mark, companion of Peter and Paul. His gospel is considered the earliest written.' },
  'saint-matthew': { name: 'St. Matthew', fact: 'Former tax collector who became an apostle and wrote the Gospel of Matthew. Patron saint of accountants.' },
  'saint-gabriel': { name: 'Archangel Gabriel', fact: 'God\'s messenger who announced the birth of Jesus to Mary and John the Baptist to Zechariah.' },
  'saint-raphael': { name: 'Archangel Raphael', fact: 'Healer and guide mentioned in the Book of Tobit. Patron of travelers, the blind, and happy meetings.' },
  'saint-thomas': { name: 'St. Thomas Aquinas', fact: 'Dominican friar and Doctor of the Church who wrote the Summa Theologica, synthesizing Christian theology and philosophy.' },
  'saint-james': { name: 'St. James the Greater', fact: 'Apostle and first martyr among the Twelve. His shrine at Santiago de Compostela is a famous pilgrimage site.' },
  'saint-andrew': { name: 'St. Andrew', fact: 'First called apostle, brother of Peter, and patron saint of Scotland. Martyred on an X-shaped cross.' },
  'saint-bartholomew': { name: 'St. Bartholomew', fact: 'Apostle who brought Christianity to Armenia and India. Tradition says he was flayed alive.' },
  'saint-philip': { name: 'St. Philip', fact: 'Apostle who brought Nathanael to Jesus. Preached in Greece and Asia Minor before his martyrdom.' },
  'saint-simon': { name: 'St. Simon the Zealot', fact: 'Apostle known for his zeal before joining Jesus. Tradition says he preached in Persia.' },
  'saint-jude': { name: 'St. Jude Thaddeus', fact: 'Apostle and patron of hopeless cases. Wrote the Epistle of Jude warning against false teachers.' },
  'saint-matthias': { name: 'St. Matthias', fact: 'Chosen to replace Judas Iscariot among the Twelve Apostles after Christ\'s Ascension.' },
  'saint-stephen': { name: 'St. Stephen', fact: 'First Christian martyr, one of the seven deacons. His witness and forgiveness of his killers converted St. Paul.' },
  'saint-lawrence': { name: 'St. Lawrence', fact: 'Roman deacon martyred by being roasted on a gridiron. Distributed Church treasures to the poor before his death.' },
  'saint-sebastian': { name: 'St. Sebastian', fact: 'Roman soldier and martyr shot with arrows for his faith. Patron of athletes and soldiers.' },
  'saint-christopher': { name: 'St. Christopher', fact: 'According to tradition, carried the Christ child across a river. Patron saint of travelers.' },
  'saint-patrick': { name: 'St. Patrick', fact: 'Apostle of Ireland who used the shamrock to explain the Trinity. Drove out paganism from Ireland.' },
  'saint-george': { name: 'St. George', fact: 'Roman soldier martyred for his faith. Legend says he slayed a dragon. Patron of England and soldiers.' },
  'saint-nicholas': { name: 'St. Nicholas', fact: 'Bishop of Myra known for generosity to the poor, especially children. Inspiration for Santa Claus.' },
  'saint-valentine': { name: 'St. Valentine', fact: 'Priest martyred in Rome, patron of lovers. Performed weddings for soldiers forbidden to marry.' },
  'saint-martin': { name: 'St. Martin of Tours', fact: 'Roman soldier who cut his cloak to share with a beggar, later became a bishop and founder of monasteries.' },
  'saint-augustine': { name: 'St. Augustine of Hippo', fact: 'Doctor of the Church whose Confessions and City of God profoundly shaped Christian theology.' },
  'saint-jerome': { name: 'St. Jerome', fact: 'Scholar and Doctor who translated the Bible into Latin (the Vulgate). Known for his learning and quick temper.' },
  'saint-bernard': { name: 'St. Bernard of Clairvaux', fact: 'Cistercian monk whose preaching sparked the Second Crusade. Known for devotion to Mary and mystical writings.' },
  'saint-dominic': { name: 'St. Dominic', fact: 'Founded the Dominican Order dedicated to preaching and study. Promoted the Rosary devotion.' },
  'saint-aquinas': { name: 'St. Thomas Aquinas', fact: 'The "Angelic Doctor" whose systematic theology remains foundational to Catholic philosophy.' },
  'saint-catherine': { name: 'St. Catherine of Alexandria', fact: 'Brilliant philosopher martyred on the breaking wheel. Patron of students, philosophers, and unmarried women.' },
  'saint-agnes': { name: 'St. Agnes', fact: 'Young Roman martyr who refused marriage to remain consecrated to Christ. Patron of young girls and purity.' },
  'saint-clare': { name: 'St. Clare of Assisi', fact: 'Founded the Poor Clares, following St. Francis\' example of radical poverty and devotion.' },
  'saint-cecilia': { name: 'St. Cecilia', fact: 'Roman martyr who sang to God as she faced death. Patron saint of musicians and church music.' },
  'saint-lucy': { name: 'St. Lucy', fact: 'Sicilian martyr whose eyes were gouged out for her faith. Patron of the blind and those with eye troubles.' },
  'saint-barbara': { name: 'St. Barbara', fact: 'Imprisoned in a tower by her father, martyred for refusing to renounce Christianity. Patron of miners and artillerymen.' },
  'saint-margaret': { name: 'St. Margaret of Antioch', fact: 'Virgin martyr who tradition says was swallowed and released by a dragon. Patron of childbirth.' },
  'saint-rita': { name: 'St. Rita of Cascia', fact: 'Augustinian nun known as patron of impossible causes, abused wives, and widows. Bore the stigmata.' },
  'saint-bernadette': { name: 'St. Bernadette Soubirous', fact: 'French peasant girl who saw 18 apparitions of Mary at Lourdes. The spring there has brought countless healings.' },
  'saint-joan': { name: 'St. Joan of Arc', fact: 'Teenage French peasant who led armies to victory following divine visions, later martyred. Patron of France.' },
  'saint-therese': { name: 'St. Therese of Lisieux', fact: 'The "Little Flower" who taught the "little way" of spiritual childhood and trust in God\'s love.' },
  'saint-monica': { name: 'St. Monica', fact: 'Mother of St. Augustine who prayed for 30 years for her son\'s conversion. Patron of mothers and wives.' },
  'saint-helena': { name: 'St. Helena', fact: 'Mother of Emperor Constantine who found the True Cross in Jerusalem. Converted her son to Christianity.' },
  'saint-elizabeth': { name: 'St. Elizabeth of Hungary', fact: 'Queen who gave away her wealth to feed the poor. Miracle of roses occurred when she was caught.' },
  'saint-anne': { name: 'St. Anne', fact: 'Mother of the Virgin Mary and grandmother of Jesus, patron of mothers, grandmothers, and women in labor.' },
  'saint-martha': { name: 'St. Martha', fact: 'Sister of Mary and Lazarus, friend of Jesus known for her hospitality and service. Patron of homemakers.' },
  'saint-magdalene': { name: 'St. Mary Magdalene', fact: 'Apostle to the apostles, first witness of the Resurrection. Tradition identifies her as a repentant sinner.' },
  'saint-veronica': { name: 'St. Veronica', fact: 'According to tradition, wiped Jesus\' face on the way to Calvary, receiving an image on her veil.' },
  'saint-anastasia': { name: 'St. Anastasia', fact: 'Early Christian martyr who ministered to prisoners. Her name means "resurrection."' },
  'saint-agatha': { name: 'St. Agatha', fact: 'Sicilian martyr tortured for refusing a Roman official. Patron of breast cancer patients and nurses.' },
  'saint-polycarp': { name: 'St. Polycarp', fact: 'Bishop of Smyrna, disciple of St. John, martyred at age 86 by being burned at the stake.' },
  'saint-ignatius': { name: 'St. Ignatius of Loyola', fact: 'Founded the Jesuits and wrote the Spiritual Exercises, transforming the Counter-Reformation.' },
  'saint-justin': { name: 'St. Justin Martyr', fact: 'Early Christian philosopher who defended the faith in writings before being beheaded in Rome.' },
  'saint-cyprian': { name: 'St. Cyprian', fact: 'Bishop of Carthage and martyr who wrote extensively on Church unity and the priesthood.' },
  'saint-ambrose': { name: 'St. Ambrose', fact: 'Bishop of Milan and Doctor of the Church who baptized St. Augustine. Influential theologian and hymn writer.' },
  'saint-chrysostom': { name: 'St. John Chrysostom', fact: 'Archbishop of Constantinople, "Golden Mouthed" preacher whose homilies remain influential today.' },
  'saint-basil': { name: 'St. Basil the Great', fact: 'Doctor of the Church who defended orthodoxy and founded hospitals and orphanages.' },
  'saint-gregory': { name: 'St. Gregory the Great', fact: 'Pope, Doctor of the Church who sent missionaries to England and reformed the liturgy.' },
};

export const animalFacts: { [key: string]: { name: string; fact: string } } = {
  'saint-francis': { name: 'Lion', fact: 'Lions are the only cats that live in groups called prides, and a lion\'s roar can be heard from 5 miles away.' },
  'saint-mary': { name: 'Elephant', fact: 'Elephants have excellent memory and can remember other elephants for decades. They also mourn their dead.' },
  'saint-joseph': { name: 'Giraffe', fact: 'Giraffes have the same number of neck vertebrae as humans (7), but each bone can be 10 inches long!' },
  'saint-anthony': { name: 'Zebra', fact: 'Each zebra has a unique stripe pattern like a fingerprint, and they can run up to 40 miles per hour.' },
  'saint-teresa': { name: 'Rhinoceros', fact: 'Despite their massive size, rhinos can run up to 30 mph and have existed for over 50 million years.' },
  'saint-michael': { name: 'Tiger', fact: 'Tigers are the largest cats in the world and excellent swimmers. Each has unique stripe patterns.' },
  'saint-peter': { name: 'Cheetah', fact: 'Cheetahs are the fastest land animals, reaching speeds of 70 mph in just 3 seconds.' },
  'saint-john': { name: 'Brown Bear', fact: 'Brown bears can weigh up to 1,500 pounds and have an incredible sense of smell, seven times better than a bloodhound.' },
  'saint-paul': { name: 'Polar Bear', fact: 'Polar bears have black skin under their white fur and can swim for days without rest in Arctic waters.' },
  'saint-luke': { name: 'Deer', fact: 'Male deer grow and shed antlers every year. These are the fastest growing living tissue in the animal kingdom.' },
  'saint-mark': { name: 'Wolf', fact: 'Wolves live in packs with complex social structures and can travel up to 30 miles in a day.' },
  'saint-matthew': { name: 'Fox', fact: 'Foxes use Earth\'s magnetic field to hunt, leaping in a specific direction to catch prey under snow.' },
  'saint-gabriel': { name: 'Gorilla', fact: 'Gorillas share 98.3% of their DNA with humans and can learn sign language to communicate.' },
  'saint-raphael': { name: 'Chimpanzee', fact: 'Chimpanzees use tools, show empathy, and have self-awareness. They can recognize themselves in mirrors.' },
  'saint-thomas': { name: 'Orangutan', fact: 'Orangutans are the largest tree-dwelling animals and among the most intelligent primates.' },
  'saint-james': { name: 'Eagle', fact: 'Eagles have incredible eyesight, about 4-8 times stronger than humans, and can spot prey from over 2 miles away.' },
  'saint-andrew': { name: 'Owl', fact: 'Owls can rotate their heads 270 degrees and have specialized feathers that allow silent flight.' },
  'saint-bartholomew': { name: 'Parrot', fact: 'Parrots can live over 80 years and some species can learn hundreds of words and phrases.' },
  'saint-philip': { name: 'Peacock', fact: 'Male peacocks have up to 200 colorful tail feathers that they display in elaborate courtship dances.' },
  'saint-simon': { name: 'Swan', fact: 'Swans mate for life and can remember people who have been kind or unkind to them.' },
  'saint-jude': { name: 'Dolphin', fact: 'Dolphins have names for each other and can recognize themselves in mirrors, showing self-awareness.' },
  'saint-matthias': { name: 'Whale', fact: 'Blue whales are the largest animals ever known to exist, with hearts the size of a small car.' },
  'saint-stephen': { name: 'Sea Turtle', fact: 'Sea turtles can hold their breath for hours and use Earth\'s magnetic field to navigate thousands of miles.' },
  'saint-lawrence': { name: 'Shark', fact: 'Sharks have been around for over 400 million years, predating dinosaurs and even trees.' },
  'saint-sebastian': { name: 'Penguin', fact: 'Emperor penguins can dive deeper than any other bird, reaching depths of over 1,800 feet.' },
  'saint-christopher': { name: 'Kangaroo', fact: 'Kangaroos can leap up to 30 feet in a single jump and use their tails as a fifth leg when moving slowly.' },
  'saint-patrick': { name: 'Koala', fact: 'Koalas sleep up to 22 hours a day and have fingerprints so similar to humans they could confuse crime scene evidence.' },
  'saint-george': { name: 'Panda', fact: 'Giant pandas spend 12-16 hours a day eating bamboo and have a special "thumb" to help grip it.' },
  'saint-nicholas': { name: 'Sloth', fact: 'Sloths move so slowly that algae grows on their fur, providing camouflage in the rainforest canopy.' },
  'saint-valentine': { name: 'Hedgehog', fact: 'Hedgehogs have about 5,000 spines and can curl into a tight ball to protect themselves from predators.' },
  'saint-martin': { name: 'Rabbit', fact: 'Rabbits can see nearly 360 degrees around them and their teeth never stop growing throughout their lives.' },
  'saint-augustine': { name: 'Squirrel', fact: 'Squirrels plant thousands of trees each year by forgetting where they buried their nuts.' },
  'saint-jerome': { name: 'Raccoon', fact: 'Raccoons have extremely sensitive front paws with thousands of nerve endings for identifying objects.' },
  'saint-bernard': { name: 'Badger', fact: 'Badgers are excellent diggers and can create extensive tunnel systems called setts that last for centuries.' },
  'saint-dominic': { name: 'Otter', fact: 'Sea otters hold hands while sleeping to prevent drifting apart and use rocks as tools to open shellfish.' },
  'saint-aquinas': { name: 'Chameleon', fact: 'Chameleons change color to communicate and regulate temperature, not primarily for camouflage.' },
  'saint-catherine': { name: 'Gecko', fact: 'Geckos can walk on ceilings using millions of tiny hairs on their feet that create molecular bonds.' },
  'saint-agnes': { name: 'Iguana', fact: 'Iguanas can hold their breath for up to 30 minutes and some species can run on water.' },
  'saint-clare': { name: 'Python', fact: 'Pythons can sense heat from warm-blooded prey using special pits on their faces.' },
  'saint-cecilia': { name: 'Flamingo', fact: 'Flamingos get their pink color from the shrimp they eat and can stand on one leg for hours without tiring.' },
  'saint-lucy': { name: 'Toucan', fact: 'Toucans have massive beaks that are surprisingly lightweight and help regulate body temperature.' },
  'saint-barbara': { name: 'Hummingbird', fact: 'Hummingbirds are the only birds that can fly backwards and their hearts beat over 1,200 times per minute!' },
  'saint-margaret': { name: 'Pelican', fact: 'Pelicans can hold up to 3 gallons of water in their beaks and have a wingspan up to 10 feet.' },
  'saint-rita': { name: 'Cardinal', fact: 'Northern cardinals are one of the few bird species where both males and females sing.' },
  'saint-bernadette': { name: 'Woodpecker', fact: 'Woodpeckers can peck 20 times per second without getting brain damage due to special skull cushioning.' },
  'saint-joan': { name: 'Horse', fact: 'Horses can sleep both lying down and standing up, and their eyes are among the largest of any land mammal.' },
  'saint-therese': { name: 'Cow', fact: 'Cows have best friends and get stressed when separated from them. They can also recognize human faces.' },
  'saint-monica': { name: 'Pig', fact: 'Pigs are highly intelligent, can learn tricks faster than dogs, and have excellent long-term memories.' },
  'saint-helena': { name: 'Sheep', fact: 'Sheep have excellent memories and can remember the faces of 50 other sheep for up to 2 years.' },
  'saint-elizabeth': { name: 'Goat', fact: 'Goats have rectangular pupils giving them 320-degree vision and excellent depth perception.' },
  'saint-anne': { name: 'Llama', fact: 'Llamas hum when they\'re content and can spit up to 15 feet when annoyed or establishing dominance.' },
  'saint-martha': { name: 'Camel', fact: 'Camels can drink 30 gallons of water in 13 minutes and their humps store fat, not water.' },
  'saint-magdalene': { name: 'Moose', fact: 'Moose are excellent swimmers and can dive up to 20 feet underwater to reach aquatic plants.' },
  'saint-veronica': { name: 'Buffalo', fact: 'Buffalo can run up to 40 mph and their horns continue growing throughout their entire lives.' },
  'saint-anastasia': { name: 'Antelope', fact: 'Pronghorn antelopes are the second-fastest land animals and can maintain 30 mph for miles.' },
  'saint-agatha': { name: 'Hippo', fact: 'Hippos can hold their breath underwater for up to 5 minutes and secrete a red, oily substance that acts as sunscreen.' },
  'saint-polycarp': { name: 'Leopard', fact: 'Leopards are powerful climbers and can carry prey twice their weight up into trees.' },
  'saint-ignatius': { name: 'Lynx', fact: 'Lynx have exceptional hearing and can detect prey moving under snow from 250 feet away.' },
  'saint-justin': { name: 'Seal', fact: 'Seals can hold their breath for up to 2 hours and dive over 6,000 feet deep in search of food.' },
  'saint-cyprian': { name: 'Walrus', fact: 'Walruses use their tusks to haul themselves onto ice and can weigh up to 4,000 pounds.' },
  'saint-ambrose': { name: 'Ferret', fact: 'Ferrets sleep 14-18 hours a day and can squeeze through spaces as small as 2 inches wide.' },
  'saint-chrysostom': { name: 'Otter', fact: 'Otters have the densest fur of any mammal with up to 1 million hairs per square inch.' },
  'saint-basil': { name: 'Beaver', fact: 'Beavers\' teeth never stop growing and their dams can be seen from space, with the longest over 2,800 feet!' },
  'saint-gregory': { name: 'Meerkat', fact: 'Meerkats take turns standing guard and have different alarm calls for different types of predators.' },
};

export const barbieFacts: { [key: string]: { name: string; fact: string } } = {
  'saint-francis': { name: 'Architect Barbie', fact: 'Architect Barbie designs buildings and spaces that improve how people live and work, combining creativity with engineering.' },
  'saint-mary': { name: 'Artist Barbie', fact: 'Artist Barbie expresses creativity through painting, sculpture, and visual arts, inspiring imagination and self-expression.' },
  'saint-joseph': { name: 'Astronaut Barbie', fact: 'Astronaut Barbie was first released in 1965, four years before the first moon landing, inspiring girls to reach for the stars!' },
  'saint-anthony': { name: 'Baker Barbie', fact: 'Baker Barbie creates delicious treats and celebrates the joy of baking, from artisan breads to elaborate cakes.' },
  'saint-teresa': { name: 'Ballerina Barbie', fact: 'Ballerina Barbie was one of the first career dolls, celebrating the grace and discipline of classical dance.' },
  'saint-michael': { name: 'Barista Barbie', fact: 'Barista Barbie crafts perfect coffee drinks and creates welcoming spaces for community gathering.' },
  'saint-peter': { name: 'Bride Barbie', fact: 'Bride Barbie celebrates love and the joy of weddings, representing one of life\'s most special moments.' },
  'saint-john': { name: 'Business Barbie', fact: 'Business Barbie leads companies and shows that women can excel in business leadership and entrepreneurship.' },
  'saint-paul': { name: 'Chef Barbie', fact: 'Chef Barbie celebrates culinary arts and has inspired many cooking-themed playsets over the years.' },
  'saint-luke': { name: 'Classic Barbie', fact: 'Classic Barbie represents the timeless original doll that has inspired generations since 1959.' },
  'saint-mark': { name: 'Cowgirl Barbie', fact: 'Cowgirl Barbie celebrates Western heritage, horseback riding, and the independent spirit of the American frontier.' },
  'saint-matthew': { name: 'Dentist Barbie', fact: 'Dentist Barbie teaches the importance of oral health and dental care careers.' },
  'saint-gabriel': { name: 'Detective Barbie', fact: 'Detective Barbie solves mysteries and represents careers in law enforcement and investigation.' },
  'saint-raphael': { name: 'DJ Barbie', fact: 'DJ Barbie spins tracks and creates musical experiences, celebrating electronic music and entertainment.' },
  'saint-thomas': { name: 'Doctor Barbie', fact: 'Doctor Barbie became a surgeon in 1973, inspiring girls to pursue careers in medicine long before it was common.' },
  'saint-james': { name: 'Engineer Barbie', fact: 'Engineer Barbie builds and designs solutions to real-world problems using science and mathematics.' },
  'saint-andrew': { name: 'Environmental Scientist Barbie', fact: 'Environmental Scientist Barbie studies ecosystems and works to protect our planet for future generations.' },
  'saint-bartholomew': { name: 'Equestrian Barbie', fact: 'Equestrian Barbie shows the special bond between riders and their horses in competitive and recreational riding.' },
  'saint-philip': { name: 'Fairy Barbie', fact: 'Fairy Barbie celebrates imagination, magic, and the power of believing in dreams.' },
  'saint-simon': { name: 'Fashion Designer Barbie', fact: 'Fashion Designer Barbie inspires creativity in clothing design and the fashion industry.' },
  'saint-jude': { name: 'Figure Skater Barbie', fact: 'Figure Skater Barbie glides on ice with grace, representing Olympic-level athleticism and artistry.' },
  'saint-matthias': { name: 'Firefighter Barbie', fact: 'Firefighter Barbie represents bravery and community service in emergency response.' },
  'saint-stephen': { name: 'Flight Attendant Barbie', fact: 'Flight Attendant Barbie travels the world ensuring passenger safety and comfort at 30,000 feet.' },
  'saint-lawrence': { name: 'Florist Barbie', fact: 'Florist Barbie creates beautiful arrangements and celebrates the art and business of flowers.' },
  'saint-sebastian': { name: 'Game Developer Barbie', fact: 'Game Developer Barbie creates video games, combining creativity with programming and technology.' },
  'saint-christopher': { name: 'Gardener Barbie', fact: 'Gardener Barbie cultivates plants and green spaces, connecting people with nature through horticulture.' },
  'saint-patrick': { name: 'Gymnast Barbie', fact: 'Gymnast Barbie demonstrates strength, flexibility, and dedication through Olympic-level gymnastics.' },
  'saint-george': { name: 'Hair Stylist Barbie', fact: 'Hair Stylist Barbie creates beautiful hairstyles and helps people feel confident about their appearance.' },
  'saint-nicholas': { name: 'Holiday Barbie', fact: 'Holiday Barbie celebrates festive seasons and special moments throughout the year with elegant fashion.' },
  'saint-valentine': { name: 'Journalist Barbie', fact: 'Journalist Barbie reports the news and represents the importance of media and communication careers.' },
  'saint-martin': { name: 'Librarian Barbie', fact: 'Librarian Barbie promotes literacy, learning, and the love of books for all ages.' },
  'saint-augustine': { name: 'Magician Barbie', fact: 'Magician Barbie performs illusions and shows the art of entertainment and wonder.' },
  'saint-jerome': { name: 'Makeup Artist Barbie', fact: 'Makeup Artist Barbie creates stunning looks for fashion, film, and special occasions.' },
  'saint-bernard': { name: 'Marine Biologist Barbie', fact: 'Marine Biologist Barbie explores ocean life and promotes conservation of marine ecosystems.' },
  'saint-dominic': { name: 'Mermaid Barbie', fact: 'Mermaid Barbie celebrates ocean fantasy and the imagination of underwater adventures.' },
  'saint-aquinas': { name: 'Mountaineer Barbie', fact: 'Mountaineer Barbie conquers peaks and inspires adventure, perseverance, and love of the outdoors.' },
  'saint-catherine': { name: 'Movie Star Barbie', fact: 'Movie Star Barbie celebrates the glamour and artistry of cinema and acting careers.' },
  'saint-agnes': { name: 'News Anchor Barbie', fact: 'News Anchor Barbie delivers important information and represents broadcast journalism careers.' },
  'saint-clare': { name: 'Nurse Barbie', fact: 'Nurse Barbie provides compassionate care and represents healthcare heroes on the front lines.' },
  'saint-cecilia': { name: 'Paleontologist Barbie', fact: 'Paleontologist Barbie digs for dinosaur fossils, making science adventurous and exciting.' },
  'saint-lucy': { name: 'Party Barbie', fact: 'Party Barbie celebrates special occasions and the joy of gathering with friends and family.' },
  'saint-barbara': { name: 'Photographer Barbie', fact: 'Photographer Barbie captures moments and tells stories through the art of photography.' },
  'saint-margaret': { name: 'Pilot Barbie', fact: 'Pilot Barbie became a commercial airline pilot in 1990, breaking gender barriers in aviation.' },
  'saint-rita': { name: 'Pirate Barbie', fact: 'Pirate Barbie sails the seas on adventures, celebrating courage and the spirit of exploration.' },
  'saint-bernadette': { name: 'Police Barbie', fact: 'Police Barbie has been protecting and serving since 1993, representing law enforcement careers.' },
  'saint-joan': { name: 'Pop Star Barbie', fact: 'Pop Star Barbie performs for audiences worldwide, celebrating music and entertainment.' },
  'saint-therese': { name: 'Princess Barbie', fact: 'Princess Barbie celebrates royalty, elegance, and fairy tale dreams.' },
  'saint-monica': { name: 'Programmer Barbie', fact: 'Programmer Barbie writes code and creates software, inspiring careers in computer science.' },
  'saint-helena': { name: 'Race Car Driver Barbie', fact: 'Race Car Driver Barbie speeds around the track, competing in motorsports at the highest level.' },
  'saint-elizabeth': { name: 'Robotics Engineer Barbie', fact: 'Robotics Engineer Barbie designs and builds robots, exploring the future of technology and automation.' },
  'saint-anne': { name: 'Rock Star Barbie', fact: 'Rock Star Barbie debuted in 1986, inspiring musical creativity and performance across generations.' },
  'saint-martha': { name: 'Scientist Barbie', fact: 'Scientist Barbie has been inspiring STEM careers since the 1960s, including roles as a computer engineer.' },
  'saint-magdalene': { name: 'Skier Barbie', fact: 'Skier Barbie glides down snowy mountains, representing winter sports and Olympic skiing.' },
  'saint-veronica': { name: 'Snowboarder Barbie', fact: 'Snowboarder Barbie carves through fresh powder on winter mountains in this exciting extreme sport.' },
  'saint-anastasia': { name: 'Soccer Player Barbie', fact: 'Soccer Player Barbie celebrates teamwork and athletic skill in the world\'s most popular sport.' },
  'saint-agatha': { name: 'Superhero Barbie', fact: 'Superhero Barbie uses her powers to help others and represents courage and strength.' },
  'saint-polycarp': { name: 'Surfer Barbie', fact: 'Surfer Barbie rides the waves and celebrates beach culture and ocean sports.' },
  'saint-ignatius': { name: 'Swimmer Barbie', fact: 'Swimmer Barbie competes in aquatic sports with speed, grace, and dedication to excellence.' },
  'saint-justin': { name: 'Teacher Barbie', fact: 'Teacher Barbie has been an educator since 1965, showing the importance of learning and teaching.' },
  'saint-cyprian': { name: 'Tennis Player Barbie', fact: 'Tennis Player Barbie serves up athletic excellence on the court with skill and sportsmanship.' },
  'saint-ambrose': { name: 'Unicorn Barbie', fact: 'Unicorn Barbie celebrates magic, fantasy, and the power of imagination and dreams.' },
  'saint-chrysostom': { name: 'Veterinarian Barbie', fact: 'Veterinarian Barbie teaches compassion for animals and the science of caring for pets.' },
  'saint-basil': { name: 'Yoga Instructor Barbie', fact: 'Yoga Instructor Barbie promotes wellness, mindfulness, and healthy living through yoga practice.' },
  'saint-gregory': { name: 'Zookeeper Barbie', fact: 'Zookeeper Barbie cares for exotic animals and educates visitors about wildlife conservation.' },
};

export const puppyFacts: { [key: string]: { name: string; fact: string } } = {
  'saint-francis': { name: 'Golden Retriever', fact: 'Golden Retrievers are one of the most popular family dogs, known for their friendly and tolerant attitudes.' },
  'saint-mary': { name: 'Black Labrador', fact: 'Black Labs are athletic, playful, and one of the most popular dog breeds in the world.' },
  'saint-joseph': { name: 'Corgi', fact: 'Corgis were bred to herd cattle in Wales - their low height helps them avoid kicks!' },
  'saint-anthony': { name: 'Husky', fact: 'Huskies can run up to 100 miles per day and have a thick double coat for arctic temperatures.' },
  'saint-teresa': { name: 'Bulldog', fact: 'Bulldogs were originally bred for bull-baiting but are now known as gentle, friendly companions.' },
  'saint-michael': { name: 'Dachshund', fact: 'Dachshunds were bred to hunt badgers - their name means "badger dog" in German!' },
  'saint-peter': { name: 'Poodle', fact: 'Poodles are one of the most intelligent dog breeds and were originally water retrievers.' },
  'saint-john': { name: 'Beagle', fact: 'Beagles have over 220 million scent receptors and are often used as detection dogs.' },
  'saint-paul': { name: 'German Shepherd', fact: 'German Shepherds are the second most popular dog breed and excel at police and military work.' },
  'saint-luke': { name: 'Shiba Inu', fact: 'Shiba Inus are the most popular companion dog in Japan and are known for their spirited personality.' },
  'saint-mark': { name: 'Labradoodle', fact: 'Labradoodles were first bred in 1989 as a hypoallergenic guide dog combining Labs and Poodles.' },
  'saint-matthew': { name: 'Cavalier King Charles', fact: 'Cavalier King Charles Spaniels are named after King Charles II who adored the breed.' },
  'saint-gabriel': { name: 'Boxer', fact: 'Boxers got their name from their playful habit of standing on hind legs and "boxing" with front paws.' },
  'saint-raphael': { name: 'Maltese', fact: 'Maltese dogs have been lap dogs for over 2,000 years and were beloved by ancient Romans.' },
  'saint-thomas': { name: 'Pug', fact: 'Pugs were bred to be companion dogs for Chinese emperors and have a 2,000-year history.' },
  'saint-james': { name: 'Bernese Mountain Dog', fact: 'Bernese Mountain Dogs were farm dogs in Switzerland, used for pulling carts and herding.' },
  'saint-andrew': { name: 'Collie', fact: 'Collies are famous for their loyalty and intelligence, made iconic by Lassie.' },
  'saint-bartholomew': { name: 'Pomeranian', fact: 'Pomeranians descended from large sled dogs and were favorites of Queen Victoria.' },
  'saint-philip': { name: 'Papillon', fact: 'Papillons are named for their butterfly-shaped ears - "papillon" means butterfly in French.' },
  'saint-simon': { name: 'Dalmatian', fact: 'Dalmatians are born completely white - their spots develop as they grow older.' },
  'saint-jude': { name: 'Pembroke Welsh Corgi', fact: 'According to Welsh legend, Corgis were used as steeds by woodland fairies.' },
  'saint-matthias': { name: 'Goldendoodle', fact: 'Goldendoodles combine Golden Retriever friendliness with Poodle intelligence and low-shedding coats.' },
  'saint-stephen': { name: 'Schnauzer', fact: 'Schnauzers were bred in Germany as farm dogs and rat catchers with their distinctive beards.' },
  'saint-lawrence': { name: 'Sheltie', fact: 'Shetland Sheepdogs are miniature Collies originally bred to herd sheep in the Shetland Islands.' },
  'saint-sebastian': { name: 'Boston Terrier', fact: 'Boston Terriers are nicknamed the "American Gentleman" for their tuxedo-like markings.' },
  'saint-christopher': { name: 'Miniature Pinscher', fact: 'Mini Pins are not miniature Dobermans - they\'re actually an older breed from Germany.' },
  'saint-patrick': { name: 'Siberian Husky', fact: 'Siberian Huskies can withstand temperatures as low as -60°F with their insulating double coat.' },
  'saint-george': { name: 'Pug Mix', fact: 'Pug mixes often inherit the Pug\'s charming personality with improved breathing from other breeds.' },
  'saint-nicholas': { name: 'Cairn Terrier', fact: 'Cairn Terriers are famous for playing Toto in The Wizard of Oz movie.' },
  'saint-valentine': { name: 'Cocker Spaniel', fact: 'Cocker Spaniels are named for their skill hunting woodcock birds and are gentle family pets.' },
  'saint-martin': { name: 'Golden Retriever', fact: 'Golden Retrievers have "soft mouths" - they can carry eggs without breaking them!' },
  'saint-augustine': { name: 'Black Labrador', fact: 'Labradors are the most popular dog breed in America for over 30 consecutive years.' },
  'saint-jerome': { name: 'Corgi', fact: 'Queen Elizabeth II owned more than 30 Corgis during her reign.' },
  'saint-bernard': { name: 'Husky', fact: 'Huskies have special adaptations including fur between their toes for warmth.' },
  'saint-dominic': { name: 'Bulldog', fact: 'Bulldogs are the mascot of many sports teams and represent determination.' },
  'saint-aquinas': { name: 'Dachshund', fact: 'Dachshunds come in three coat types: smooth, longhaired, and wirehaired.' },
  'saint-catherine': { name: 'Poodle', fact: 'Poodles come in three sizes: Standard, Miniature, and Toy, all equally intelligent.' },
  'saint-agnes': { name: 'Beagle', fact: 'Beagles have been bred as hunting dogs for over 500 years in England.' },
  'saint-clare': { name: 'German Shepherd', fact: 'German Shepherds are used as guide dogs, therapy dogs, and search-and-rescue dogs.' },
  'saint-cecilia': { name: 'Shiba Inu', fact: 'Shiba Inus are known for their "Shiba scream" - a unique vocalization when excited or upset.' },
  'saint-lucy': { name: 'Labradoodle', fact: 'Labradoodles have three coat types: wool, fleece, and hair, with varying curl patterns.' },
  'saint-barbara': { name: 'Cavalier King Charles', fact: 'Cavaliers are known as "comforter spaniels" for their gentle and affectionate nature.' },
  'saint-margaret': { name: 'Boxer', fact: 'Boxers were one of the first breeds to be employed as police dogs in Germany.' },
  'saint-rita': { name: 'Maltese', fact: 'Maltese dogs don\'t shed and are considered hypoallergenic, perfect for allergy sufferers.' },
  'saint-bernadette': { name: 'Pug', fact: 'Pugs are known for their expressive faces and can make many human-like expressions.' },
  'saint-joan': { name: 'Bernese Mountain Dog', fact: 'Bernese Mountain Dogs are known as "Berners" and love cold weather and snow.' },
  'saint-therese': { name: 'Collie', fact: 'Collies can learn a new command in as few as 5 repetitions due to their high intelligence.' },
  'saint-monica': { name: 'Pomeranian', fact: 'Pomeranians are one of the most popular toy breeds and have fluffy double coats.' },
  'saint-helena': { name: 'Papillon', fact: 'Papillons are one of the oldest toy spaniel breeds, dating back over 700 years.' },
  'saint-elizabeth': { name: 'Dalmatian', fact: 'Dalmatians were historically "coach dogs" that ran alongside horse-drawn carriages.' },
  'saint-anne': { name: 'Pembroke Welsh Corgi', fact: 'Pembroke Corgis don\'t have tails, while Cardigan Corgis do - an easy way to tell them apart!' },
  'saint-martha': { name: 'Goldendoodle', fact: 'Goldendoodles come in various sizes from mini to standard, depending on the Poodle parent.' },
  'saint-magdalene': { name: 'Schnauzer', fact: 'Schnauzers come in three sizes: Miniature, Standard, and Giant, all with signature beards.' },
  'saint-veronica': { name: 'Sheltie', fact: 'Shelties are incredibly vocal dogs known for their distinctive bark and love of "talking."' },
  'saint-anastasia': { name: 'Boston Terrier', fact: 'Boston Terriers were the first dog breed developed in America, in the 1870s.' },
  'saint-agatha': { name: 'Miniature Pinscher', fact: 'Min Pins are called the "King of Toys" for their confident and fearless personalities.' },
  'saint-polycarp': { name: 'Siberian Husky', fact: 'Huskies are known escape artists and need secure fencing as they love to explore.' },
  'saint-ignatius': { name: 'Pug Mix', fact: 'Designer Pug mixes like Puggles and Chugs combine the best traits of both parent breeds.' },
  'saint-justin': { name: 'Cairn Terrier', fact: 'Cairn Terriers are one of the oldest terrier breeds from the Scottish Highlands.' },
  'saint-cyprian': { name: 'Cocker Spaniel', fact: 'Cocker Spaniels were America\'s most popular breed from 1936 to 1952.' },
  'saint-ambrose': { name: 'Golden Retriever', fact: 'Goldens are natural swimmers with water-repellent coats and webbed feet.' },
  'saint-chrysostom': { name: 'Black Labrador', fact: 'Labs come in three colors: black, yellow, and chocolate, with black being most common.' },
  'saint-basil': { name: 'Corgi', fact: 'Corgis are surprisingly fast runners and can reach speeds up to 25 mph.' },
  'saint-gregory': { name: 'Husky', fact: 'Huskies have blue eyes, brown eyes, or one of each - called heterochromia.' },
};


export const santaFacts: { [key: string]: { name: string; fact: string } } = {
  'saint-francis': { name: 'Santa Claus', fact: 'Santa Claus is based on St. Nicholas, a generous bishop who secretly gave gifts to the poor. He travels the world in one night!' },
  'saint-mary': { name: 'Rudolph', fact: 'Rudolph the Red-Nosed Reindeer was created in 1939 for a Montgomery Ward coloring book. His glowing nose guides Santa\'s sleigh through foggy nights.' },
  'saint-joseph': { name: 'Frosty the Snowman', fact: 'Frosty came to life with a magic silk hat. Snowmen have been built for centuries as winter fun - the oldest known drawing dates to 1380!' },
  'saint-anthony': { name: 'Christmas Tree', fact: 'The tradition of decorating Christmas trees began in 16th century Germany. Queen Victoria popularized it worldwide in the 1840s.' },
  'saint-teresa': { name: 'Christmas Elf', fact: 'Santa\'s elves work year-round making toys in his North Pole workshop. They\'re known for their cheerful attitudes and pointed ears!' },
  'saint-michael': { name: 'Gingerbread Man', fact: 'Gingerbread cookies date back to medieval times. The first gingerbread men were made for Queen Elizabeth I as likenesses of important guests!' },
  'saint-peter': { name: 'Christmas Stocking', fact: 'The tradition comes from St. Nicholas dropping gold coins down a chimney - they landed in stockings hung to dry by the fire!' },
  'saint-john': { name: 'Christmas Present', fact: 'The tradition of gift-giving represents the gifts the Wise Men brought to baby Jesus: gold, frankincense, and myrrh.' },
  'saint-paul': { name: 'Candy Cane', fact: 'Candy canes were originally straight white sticks. The crook shape represents a shepherd\'s staff, and the red stripes were added later!' },
  'saint-luke': { name: 'Santa\'s Sleigh', fact: 'Santa\'s sleigh is pulled by eight reindeer: Dasher, Dancer, Prancer, Vixen, Comet, Cupid, Donner, and Blitzen!' },
  'saint-mark': { name: 'Christmas Angel', fact: 'Angels announced Jesus\' birth to shepherds. The angel tree topper tradition began in Germany in the 1800s.' },
  'saint-matthew': { name: 'Christmas Wreath', fact: 'The circular wreath symbolizes eternity with no beginning or end. Holly and evergreens represent everlasting life in winter.' },
  'saint-gabriel': { name: 'Christmas Penguin', fact: 'While penguins don\'t live at the North Pole (they\'re Antarctic!), they\'ve become beloved winter mascots for their tuxedo-like appearance.' },
  'saint-raphael': { name: 'Polar Bear', fact: 'Polar bears are the largest land carnivores. Their white fur helps them blend into Arctic snow while waiting for seals.' },
  'saint-thomas': { name: 'Cardinal Bird', fact: 'Cardinals don\'t migrate and their bright red color against white snow makes them a beloved Christmas symbol!' },
  'saint-james': { name: 'Hot Cocoa', fact: 'Hot chocolate was invented by the Mayans over 2000 years ago! Adding marshmallows became popular in the 1900s.' },
  'saint-andrew': { name: 'Christmas Cottage', fact: 'Cozy cottages with snow on the roof and smoke from the chimney represent warmth and family during the cold winter season.' },
  'saint-bartholomew': { name: 'Christmas Star', fact: 'The Star of Bethlehem guided the Wise Men to baby Jesus. Some scientists think it may have been a rare planetary conjunction!' },
  'saint-philip': { name: 'Gingerbread House', fact: 'Gingerbread houses became popular after the Brothers Grimm published Hansel and Gretel in 1812!' },
  'saint-simon': { name: 'Mrs. Claus', fact: 'Mrs. Claus first appeared in stories in 1849. She helps Santa manage the elves and makes sure he has warm cookies and milk!' },
  'saint-jude': { name: 'Winter Owl', fact: 'Snowy owls are active during winter and can spot prey under snow. In Harry Potter, Hedwig made white owls extra magical!' },
  'saint-matthias': { name: 'Nutcracker', fact: 'Nutcracker soldiers guard against evil spirits. The famous Nutcracker ballet by Tchaikovsky premiered in 1892!' },
  'saint-stephen': { name: 'Mistletoe', fact: 'Kissing under mistletoe is a tradition from ancient times when it symbolized love and peace. Vikings believed it could resurrect the dead!' },
  'saint-lawrence': { name: 'Winter Fox', fact: 'Arctic foxes change their coat from brown to white in winter for camouflage. Their fluffy tails keep them warm while sleeping!' },
  'saint-sebastian': { name: 'Christmas Ornament', fact: 'Glass ornaments originated in Lauscha, Germany in the 1800s. F.W. Woolworth made a fortune selling them in America!' },
  'saint-christopher': { name: 'Snowflake', fact: 'No two snowflakes are exactly alike! Wilson Bentley photographed over 5,000 snowflakes, calling them "ice flowers."' },
  'saint-patrick': { name: 'Christmas Mouse', fact: '"Twas the Night Before Christmas" mentions "not a creature was stirring, not even a mouse." Mice love the warmth of holiday homes!' },
  'saint-george': { name: 'Poinsettia', fact: 'Poinsettias are native to Mexico. Legend says a poor girl\'s humble weeds transformed into beautiful red flowers as a Christmas miracle!' },
  'saint-nicholas': { name: 'Jack Frost', fact: 'Jack Frost is a personification of winter cold, painting frost patterns on windows. He appears in folklore from many cultures!' },
  'saint-valentine': { name: 'Christmas Bells', fact: 'Bells announce joyous occasions! Church bells ring on Christmas Eve, and "Jingle Bells" is one of the most popular songs ever written.' },
  'saint-martin': { name: 'Winter Fawn', fact: 'Young deer are called fawns. In winter, deer grow thicker coats and their spots fade to help them blend into the snowy forest.' },
  'saint-augustine': { name: 'Ice Skating', fact: 'Ice skating has been around for over 3,000 years! The first skates were made from animal bones tied to shoes.' },
  'saint-jerome': { name: 'Christmas Robin', fact: 'Robins are beloved Christmas symbols in Britain. Legend says a robin\'s breast turned red from fanning flames to keep baby Jesus warm!' },
  'saint-bernard': { name: 'Cozy Fireplace', fact: 'Santa comes down the chimney because St. Nicholas was said to drop gifts down chimneys. Leaving cookies nearby welcomes him!' },
  'saint-dominic': { name: 'Winter Seal', fact: 'Seals are perfectly adapted to cold water with thick blubber. Harbor seal pups are sometimes called "silkies" in folklore!' },
  'saint-aquinas': { name: 'Snow Globe', fact: 'Snow globes were invented in Austria in 1900. The first famous one contained a miniature Eiffel Tower!' },
  'saint-catherine': { name: 'Winter Bunny', fact: 'Snowshoe hares turn white in winter for camouflage. Their large feet act like snowshoes to help them hop on snow!' },
  'saint-agnes': { name: 'Christmas Candle', fact: 'Candles in windows date to colonial times, welcoming travelers. Irish families lit them to signal priests that Mass was welcome!' },
  'saint-clare': { name: 'Holly Berries', fact: 'Holly\'s sharp leaves and red berries symbolize Christ\'s crown of thorns and drops of blood. It stays green all winter!' },
  'saint-cecilia': { name: 'Rudolph', fact: 'Rudolph is the most famous reindeer of all! Gene Autry\'s 1949 song about him became one of the best-selling singles ever.' },
  'saint-lucy': { name: 'Frosty the Snowman', fact: 'The song "Frosty the Snowman" was written in 1950 and became a holiday classic, inspiring TV specials loved by generations.' },
  'saint-barbara': { name: 'Christmas Tree', fact: 'Americans buy 25-30 million real Christmas trees each year. The tallest tree ever displayed was 221 feet in Seattle!' },
  'saint-margaret': { name: 'Christmas Elf', fact: 'Elves are said to be very fast at making toys. The Elf on the Shelf became a modern tradition to watch over children!' },
  'saint-rita': { name: 'Gingerbread Man', fact: '"Run, run, as fast as you can! You can\'t catch me, I\'m the Gingerbread Man!" This fairy tale has been told since 1875.' },
  'saint-bernadette': { name: 'Christmas Stocking', fact: 'The largest Christmas stocking ever made was 168 feet long and held toys for an entire village!' },
  'saint-joan': { name: 'Christmas Present', fact: 'Americans spend over $1 trillion on holiday gifts each year. The joy of giving is what makes Christmas so special!' },
  'saint-therese': { name: 'Candy Cane', fact: 'About 1.76 billion candy canes are produced each year. That\'s enough to stretch around the Earth 35 times!' },
  'saint-monica': { name: 'Santa\'s Sleigh', fact: 'NORAD tracks Santa\'s sleigh every Christmas Eve! The tradition started in 1955 due to a misprinted phone number.' },
  'saint-helena': { name: 'Christmas Angel', fact: 'The Archangel Gabriel is said to have announced the birth of Jesus. Angels represent messengers of good news!' },
  'saint-elizabeth': { name: 'Christmas Wreath', fact: 'Advent wreaths with four candles count down the weeks until Christmas. Each Sunday, a new candle is lit!' },
  'saint-anne': { name: 'Christmas Penguin', fact: 'Emperor penguins huddle together in Antarctic winter, taking turns in the warm center. True teamwork!' },
  'saint-martha': { name: 'Polar Bear', fact: 'Coca-Cola\'s polar bear ads made them Christmas icons since 1993. Real polar bears have black skin under white fur!' },
  'saint-magdalene': { name: 'Cardinal Bird', fact: 'Cardinals mate for life and the male feeds the female during nesting. They\'re symbols of love and hope!' },
  'saint-veronica': { name: 'Hot Cocoa', fact: 'The first hot chocolate was spicy and bitter! Adding sugar and milk to make it sweet came much later in Europe.' },
  'saint-anastasia': { name: 'Christmas Cottage', fact: 'Many people decorate gingerbread houses to look like snowy cottages. It\'s become a beloved family tradition!' },
  'saint-agatha': { name: 'Christmas Star', fact: 'Star-shaped cookies and decorations remind us of the Star of Bethlehem that shone over the stable.' },
  'saint-polycarp': { name: 'Gingerbread House', fact: 'The world\'s largest gingerbread house was built in Texas in 2013 - big enough to walk inside!' },
  'saint-ignatius': { name: 'Mrs. Claus', fact: 'Mrs. Claus is often shown with rosy cheeks and round glasses, baking cookies and caring for the reindeer.' },
  'saint-justin': { name: 'Winter Owl', fact: 'Great horned owls don\'t migrate and hunt throughout winter. Their hooting can be heard on quiet snowy nights!' },
  'saint-cyprian': { name: 'Nutcracker', fact: 'Traditional German nutcrackers were given as gifts for good luck. The larger the nutcracker, the more protection it provided!' },
  'saint-ambrose': { name: 'Mistletoe', fact: 'Mistletoe is actually a parasitic plant that grows on tree branches! Despite this, it\'s been prized for centuries.' },
  'saint-chrysostom': { name: 'Winter Fox', fact: 'Red foxes are adaptable and live in many habitats. Their bushy tails, called "brushes," wrap around them for warmth!' },
  'saint-basil': { name: 'Christmas Ornament', fact: 'Handblown glass ornaments from Germany were first brought to America in the 1880s by Woolworth stores.' },
  'saint-gregory': { name: 'Snowflake', fact: 'A single snowstorm can drop 39 trillion snowflakes! Each one forms a unique hexagonal crystal pattern.' },
};

export const spaceFacts: { [key: string]: { name: string; fact: string } } = {
  'saint-francis':     { name: 'Sun',           fact: 'The Sun is so massive it makes up 99.86% of all the mass in our solar system!' },
  'saint-mary':        { name: 'Earth',         fact: 'Earth is the only planet not named after a god, and it travels around the Sun at 67,000 mph.' },
  'saint-joseph':      { name: 'Mars',          fact: 'A day on Mars is just 37 minutes longer than an Earth day. Its red color comes from rusty iron in the soil.' },
  'saint-anthony':     { name: 'Jupiter',       fact: 'Jupiter is so big that all the other planets in the solar system could fit inside it.' },
  'saint-teresa':      { name: 'Saturn',        fact: 'Saturn’s rings are made mostly of ice and rock, and some chunks are as big as houses!' },
  'saint-michael':     { name: 'Moon',          fact: 'The Moon is slowly drifting away from Earth, about 1.5 inches farther every year.' },
  'saint-peter':       { name: 'Mercury',       fact: 'Mercury is the smallest planet and the closest to the Sun. A year there lasts only 88 Earth days.' },
  'saint-john':        { name: 'Venus',         fact: 'Venus is the hottest planet, even hotter than Mercury, because of its thick greenhouse atmosphere.' },
  'saint-paul':        { name: 'Neptune',       fact: 'Neptune has the strongest winds in the solar system, blowing at over 1,200 mph.' },
  'saint-luke':        { name: 'Uranus',        fact: 'Uranus rotates on its side, so its poles take turns facing the Sun for decades at a time.' },
  'saint-mark':        { name: 'Pluto',         fact: 'Pluto was reclassified as a dwarf planet in 2006. Its largest moon, Charon, is half its size!' },
  'saint-matthew':     { name: 'Astronaut',     fact: 'Astronauts grow about 2 inches taller in space because there’s no gravity squishing their spine.' },
  'saint-gabriel':     { name: 'Rocket',        fact: 'A rocket needs to travel 25,000 mph to escape Earth’s gravity and reach outer space.' },
  'saint-raphael':     { name: 'Space Shuttle', fact: 'NASA’s Space Shuttle flew 135 missions between 1981 and 2011, ferrying astronauts to orbit and back.' },
  'saint-thomas':      { name: 'UFO',           fact: 'UFO stands for Unidentified Flying Object. Most reported UFOs turn out to be planes, balloons, or weather!' },
  'saint-james':       { name: 'Alien',         fact: 'Scientists are searching for alien life on Mars, on Jupiter’s moon Europa, and on planets around other stars.' },
  'saint-andrew':      { name: 'Satellite',     fact: 'There are over 8,000 active satellites orbiting Earth right now, used for GPS, weather, and TV.' },
  'saint-bartholomew': { name: 'Space Station', fact: 'The International Space Station orbits Earth every 90 minutes, so astronauts see 16 sunrises a day!' },
  'saint-philip':      { name: 'Galaxy',        fact: 'Our Milky Way galaxy contains over 100 billion stars, and there are trillions of galaxies in the universe.' },
  'saint-simon':       { name: 'Black Hole',    fact: 'A black hole’s gravity is so strong that not even light can escape from inside it.' },
  'saint-jude':        { name: 'Nebula',        fact: 'A nebula is a giant cloud of gas and dust in space — and many are the birthplaces of new stars!' },
  'saint-matthias':    { name: 'Comet',         fact: 'Comets are sometimes called “dirty snowballs” because they’re made of ice, dust, and rock.' },
  'saint-stephen':     { name: 'Asteroid',      fact: 'Most asteroids in our solar system live in the Asteroid Belt between Mars and Jupiter.' },
  'saint-lawrence':    { name: 'Star Cluster',  fact: 'Some star clusters contain millions of stars all born from the same giant cloud of gas.' },
  'saint-sebastian':   { name: 'Telescope',     fact: 'The James Webb Space Telescope can see light from galaxies that formed over 13 billion years ago.' },
  'saint-christopher': { name: 'Mars Rover',    fact: 'The Perseverance rover landed on Mars in 2021 and brought along a tiny helicopter named Ingenuity.' },
  'saint-patrick':     { name: 'Lunar Lander',  fact: 'In 1969, the Apollo 11 lunar lander carried the first humans to walk on the Moon.' },
  'saint-george':      { name: 'Solar System',  fact: 'Our solar system has 8 planets, 5 dwarf planets, and over 200 known moons.' },
  'saint-nicholas':    { name: 'Orion',         fact: 'Orion is one of the easiest constellations to spot in winter. Look for the three stars of his belt!' },
  'saint-valentine':   { name: 'Meteor',        fact: 'A “shooting star” isn’t a star at all — it’s a meteor burning up in Earth’s atmosphere.' },
  'saint-martin':      { name: 'Supernova',     fact: 'A supernova is the explosion of a dying star, briefly outshining an entire galaxy.' },
  'saint-augustine':   { name: 'Space Helmet',  fact: 'Astronaut helmets have a thin layer of real gold on the visor to protect their eyes from the Sun.' },
};

// Helper function to get a fact based on theme and symbol
export function getCardFact(theme: 'saints' | 'animals' | 'barbie' | 'puppy' | 'santa' | 'space' | 'minecraft', symbol: string): { name: string; fact: string } | null {
  switch (theme) {
    case 'saints':
      return saintFacts[symbol] || null;
    case 'animals':
      return animalFacts[symbol] || null;
    case 'barbie':
      return barbieFacts[symbol] || null;
    case 'puppy':
      return puppyFacts[symbol] || null;
    case 'santa':
      return santaFacts[symbol] || null;
    case 'space':
      return spaceFacts[symbol] || null;
    case 'minecraft':
      return minecraftFacts[symbol] || null;
    default:
      return null;
  }
}
